# $schema: https://json.schemastore.org/github-workflow
name: 'Build and release plugin (dev)'

on:
  pull_request:
    branches:
      - jellyfin-10.10.x
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:
    inputs:
      dotnet-version:
        type: string
        required: false
        default: "9.0"
        description: Dotnet version.
      repo-slug:
        type: string
        required: false
        default: "jellyfin-dev"
        description: Repository slug.
jobs:
  test:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/test.yaml@master
    with:
      dotnet-version: ${{ inputs.dotnet-version || '9.0' }}

  build:
    uses: ./.github/workflows/build.yml

  upload-repo:
    if: ${{ contains(github.repository, 'lyarenei/') }}
    needs: build
    uses: ./.github/workflows/upload-repo.yml
    with:
      repo: ${{ inputs.repo-slug || 'jellyfin-dev' }}
    secrets:
      host: ${{ secrets.DEPLOY_HOST }}
      user: ${{ secrets.DEPLOY_USER }}
      key: ${{ secrets.DEPLOY_KEY }}

  update-manifest:
    if: ${{ contains(github.repository, 'lyarenei/') }}
    needs: upload-repo
    uses: ./.github/workflows/publish.yml
    with:
      repo: ${{ inputs.repo-slug || 'jellyfin-dev' }}
    secrets:
      host: ${{ secrets.DEPLOY_HOST }}
      user: ${{ secrets.DEPLOY_USER }}
      key: ${{ secrets.DEPLOY_KEY }}
