# $schema: https://json.schemastore.org/github-workflow
name: 'Upload plugin to repository'

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
    secrets:
      host:
        required: true
      user:
        required: true
      key:
        required: true

jobs:
  upload-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v6
        with:
          name: build-artifact

      - name: Ensure Destination Path Exists
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.user }}
          key: ${{ secrets.key }}
          script_stop: true
          script: |-
            mkdir -p "/var/www/repos/${{ inputs.repo }}/${{ github.repository }}/${{ inputs.version }}" || exit 1

      - name: Upload Jellyfin Plugin Repository Assets
        uses: burnett01/rsync-deployments@796cf0d5e4b535745ce49d7429f77cf39e25ef39 # v7.0.1
        with:
          switches: -vrptz
          path: ./*.zip
          remote_path: /var/www/repos/${{ inputs.repo }}/${{ github.repository }}/${{ inputs.version }}
          remote_host: ${{ secrets.host }}
          remote_user: ${{ secrets.user }}
          remote_key: ${{ secrets.key }}
